### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### POST createUser
POST http://localhost:8080/user
Content-Type: application/json

{
    "userName" : "user4",
    "userProfileUrl" : ""
}

### POST followCheck
POST http://localhost:8080/relation/follow
Content-Type: application/json

{
  "followingId": 4,
  "followerId": 3
}

### POST unfollowCheck
POST http://localhost:8080/relation/unfollow
Content-Type: application/json

{
  "followingId": 1,
  "followerId": 3
}

### GET findFollowerCountById
GET http://localhost:8080/user/3/following

### GET findFollowingCountById
GET http://localhost:8080/user/4/follower

### GET findUserProfileById
GET http://localhost:8080/user/2